### ISSUE TITLE
Drag and drop doesn't seem to work on MacOS High Sierra 10.13.4

### ISSUE THREAD

**Issue by billhorsman** [christopherwk210/bamboo#1]
Nice app! Thanks for putting this together.

If I drag a file from Finder and drop it in the window, nothing happens. Using the "Add Images" button works fine though.

![no-drop](https://user-images.githubusercontent.com/19054/39250799-9e008d9e-4899-11e8-8b16-34d6ac479136.gif)

(using Bamboo v1.0.0)

**Comment by christopherwk210** [comment]
Thanks for the heads up! Issue fixed in 30c853ec88ab2ff830f722b782e61f876e2a414b. I've also uploaded a new [release](https://github.com/christopherwk210/bamboo/releases/tag/v1.0.1) 😄
