### ISSUE TITLE
v1.2.0 bamboo-darwin-x64.zip is not for windows its files for mac...

### ISSUE THREAD

**Issue by raykai** [christopherwk210/bamboo#15]
v1.2.0 bamboo-darwin-x64.zip is not for windows its files for mac...
hope to see a 64bit for windows.

**Comment by christopherwk210** [comment]
![Screen Shot 2020-01-15 at 12 44 06 PM](https://user-images.githubusercontent.com/13367277/72469744-e8e17a80-3794-11ea-81d5-d16436d7d6bd.png)
