### ISSUE TITLE
[Feature] Open folder

### ISSUE THREAD

**Issue by SirGryphin** [christopherwk210/bamboo#3]
I really like this program but I would love to be able to drag and drop a folder onto it to shrink it.

I use this program to shrink images in my ebooks to make the alot smaller in size it would be awsome to be able to drag epub on the program and it shrink it.

**Comment by christopherwk210** [comment]
The ability to drop folders into the app has been added into the latest release which you can get [here](https://github.com/christopherwk210/bamboo/releases).

Reading epubs or any file that isn't an image is out of the scope of the app, so I probably won't be adding that.
